import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Configure Calibri from your public folder structure
const calibri = localFont({
  src: [
    {
      path: "/fonts/Calibri.woff2", // Points directly to public/fonts/Calibri.woff2
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/Calibri-Bold.woff2", // Points directly to public/fonts/Calibri-Bold.woff2
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-calibri",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html 
      lang="en" 
      className={`${calibri.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
